package com.example.ui_yugiohcardlist.ui.test

const val TAG_YUGIOH_CARD_SEARCH_BAR = "TAG_YUGIOH_CARD_SEARCH_BAR"
const val TAG_YUGIOH_CARD_NAME = "TAG_YUGIOH_CARD_NAME"
const val TAG_YUGIOH_CARD_DESC = "TAG_YUGIOH_CARD_NAME"
const val TAG_YUGIOH_CARD_FILTER_BTN = "TAG_YUGIOH_CARD_FILTER_BTN"
const val TAG_YUGIOH_CARD_FILTER_DIALOG = "TAG_YUGIOH_CARD_FILTER_DIALOG"
const val TAG_YUGIOH_CARD_FILTER_DIALOG_DONE = "TAG_YUGIOH_CARD_FILTER_DIALOG_DONE"
const val TAG_YUGIOH_CARD_FILTER_DESC = "TAG_YUGIOH_CARD_FILTER_DESC"
const val TAG_YUGIOH_CARD_FILTER_ASC = "TAG_YUGIOH_CARD_FILTER_ASC"